// Implementation borrowed from https://github.com/ButterscotchV/AXSlime
public enum HapticNodeBinding : byte {
    RightThigh,
    RightCalf,
    LeftThigh,
    LeftCalf,
    RightUpperArm,
    RightForeArm,
    LeftUpperArm,
    LeftForeArm,
    Chest,
    RightFoot,
    LeftFoot,
    RightHand,
    LeftHand,
    RightShoulder,
    LeftShoulder,
    Head,
    Hips,
    ChestFront,
    HipsFront,
    ChestBack,
    HipsBack,
    ChestAndHips,
    ChestAndHipsFront,
    ChestAndHipsBack
}
